# config/packages/easy_admin.yaml
easy_admin:
  formats:
    datetime: 'd/m/Y H:i:s'
    date: 'd/m/Y'
    time: 'H:i'
  design:
    menu:
      - { label: 'Site Web', route: 'home', icon: home }
      - label: 'Utilisateurs'
        icon: 'users'
        children:
          - { label: 'Orbis Primus', icon: 'certificate', entity: 'Orbis_Primus' }
          - { label: 'Orbis Secondus', icon: 'asterisk', entity: 'Orbis_Secondus'}
          - { label: 'Orbis Tertius', icon: 'times', entity: 'Orbis_Tertius'}
      - label: 'Autres'
      - { label: 'Évènements', icon: 'calendar-alt', entity: 'Event' }
      - { label: 'Projets', icon: 'project-diagram', entity: 'Project' }
    assets:
      favicon:
        path: '/bundles/easyadmin/images/projet/Logo Taliesin.webp'
        mime_type: 'image/webp'
  site_name: '<img src="/bundles/easyadmin/images/projet/Logo Taliesin.webp" /> Collectif Taliesin'
  entities:
    Orbis_Primus:
      class: App\Entity\User
      label: 'Orbis Primus'
      new:
        title: 'Créer un nouvel %%entity_label%%'
        fields:
          - property: 'rank'
            type: 'choice'
            type_options:
              expanded: true
              data: '2'
              choices: { 'Orbis Primus': '2'}
          - property: 'roles'
            type: 'choice'
            type_options:
              expanded: true
              multiple: true
              data: ["ROLE_ADMIN"]
              choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' }
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
        fields:
          - property: 'rank'
            type: 'choice'
            type_options:
              expanded: true
              choices: { 'Orbis Primus': '2', 'Orbis Secondus': '1', 'Orbis Tertius': '0' }
          - property: 'roles'
            type: 'choice'
            type_options:
              expanded: true
              multiple: true
              data: ["ROLE_ADMIN"]
              choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' }
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
      search:
        sort: ['enabled', 'DESC']
      list:
        actions:
          show: { name: show, type: method, label: 'Plus', icon: eye }
          edit: { name: edit, type: method, label: 'Éditer', icon: pencil }
          delete: { name: delete, type: method, label: 'Supprimer', icon: trash }
          new: { name: new, type: method, label: 'Ajouter', icon: user-plus }
        dql_filter: 'entity.rank = 2'
        fields:
            - { property: 'enabled', label: 'Active' }
            - { property: 'username', label: 'Utilisateur' }
            - { property: 'name', label: 'Nom' }
            - { property: 'email', label: 'Contact' }
            - { property: 'formatedroles', label: 'Role'}
            - { property: 'formatedrank', label: 'Rang' }
            - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
            - { property: 'formatedevent', label: 'Évènement', type: string}
        title: 'Liste des %%entity_label%%'
        sort: ['enabled', 'DESC']
      show:
        title: '%%entity_label%% n°(#%%entity_id%%)'
        fields:
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom Utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { property: 'formatedroles', label: 'Role'}
          - { property: 'formatedrank', label: 'Rang' }
          - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
          - { property: 'event', label: 'Inscris à l''évènement'}
          - { property: 'enabled', label: 'Active', help: 'L''utilisateur est autorisé à se connecter'}
      form:
        fields:
          - { type: 'group', columns: 6, label: 'Informations personnelles', icon: 'user' }
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom Utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { type: 'group', columns: 5, label: 'Informations Complémentaires', icon: 'code' }
          - property: 'plainPassword'
            type: 'repeated'
            type_options:
              type: Symfony\Component\Form\Extension\Core\Type\PasswordType
              required: true
              first_options: { label: 'Mot de passe' }
              second_options: { label: 'Confirmer le mot de passe' }
              invalid_message: fos_user.password.mismatch
    Orbis_Secondus:
      class: App\Entity\User
      label: 'Orbis Secondus'
      new:
        title: 'Créer un nouvel %%entity_label%%'
        fields:
          - property: 'rank'
            type: 'choice'
            type_options:
              expanded: true
              data: '0'
              choices: { 'Orbis Tertius': '0'}
          - property: 'roles'
            type: 'choice'
            type_options:
              expanded: true
              multiple: true
              data: ["ROLE_USER"]
              choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' }
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
        fields:
          - property: 'rank'
            type: 'choice'
            type_options:
              expanded: true
              choices: { 'Orbis Primus': '2', 'Orbis Secondus': '1', 'Orbis Tertius': '0' }
          - property: 'roles'
            type: 'choice'
            type_options:
              expanded: true
              multiple: true
              data: ["ROLE_USER"]
              choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' }
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
      search:
        sort: ['enabled', 'DESC']
      list:
        actions:
          show: { name: show, type: method, label: 'Plus', icon: eye }
          edit: { name: edit, type: method, label: 'Éditer', icon: pencil }
          delete: { name: delete, type: method, label: 'Supprimer', icon: trash }
          new: { name: new, type: method, label: 'Ajouter', icon: user-plus }
        dql_filter: 'entity.rank = 1'
        fields:
          - { property: 'enabled', label: 'Active' }
          - { property: 'username', label: 'Utilisateur' }
          - { property: 'name', label: 'Nom' }
          - { property: 'email', label: 'Contact' }
          - { property: 'formatedroles', label: 'Role' }
          - { property: 'formatedrank', label: 'Rang' }
          - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
          - { property: 'formatedevent', label: 'Évènement', type: string}
          - { property: 'formatedevent', label: 'Évènement', type: string}
        title: 'Liste des %%entity_label%%'
        sort: ['enabled', 'DESC']
      show:
        title: '%%entity_label%% n°(#%%entity_id%%)'
        fields:
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom Utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { property: 'formatedroles', label: 'Role'}
          - { property: 'formatedrank', label: 'Rang' }
          - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
          - { property: 'event', label: 'Inscris à l''évènement'}
          - { property: 'enabled', label: 'Active', help: 'L''utilisateur est autorisé à se connecter'}
      form:
        fields:
          - { type: 'group', columns: 6, label: 'Informations personnelles', icon: 'user' }
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom Utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { type: 'group', columns: 5, label: 'Informations Complémentaires', icon: 'code' }
          - property: 'plainPassword'
            type: 'repeated'
            type_options:
              type: Symfony\Component\Form\Extension\Core\Type\PasswordType
              required: true
              first_options: { label: 'Mot de passe' }
              second_options: { label: 'Confirmer le mot de passe' }
              invalid_message: fos_user.password.mismatch
    Orbis_Tertius:
      class: App\Entity\User
      label: 'Orbis Tertius'
      new:
        title: 'Créer un nouvel %%entity_label%%'
        fields:
          - property: 'rank'
            type: 'choice'
            type_options:
              expanded: true
              data: '0'
              choices: { 'Orbis Tertius': '0'}
          - property: 'roles'
            type: 'choice'
            type_options:
              expanded: true
              multiple: true
              data: ["ROLE_USER"]
              choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' }
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
        fields:
          - property: 'rank'
            type: 'choice'
            type_options:
              expanded: true
              choices: { 'Orbis Primus': '2', 'Orbis Secondus': '1', 'Orbis Tertius': '0' }
          - property: 'roles'
            type: 'choice'
            type_options:
              expanded: true
              multiple: true
              data: ["ROLE_USER"]
              choices: { 'Utilisateur': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' }
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
      search:
        sort: ['enabled', 'DESC']
      list:
        actions:
          show: { name: show, type: method, label: 'Plus', icon: eye }
          edit: { name: edit, type: method, label: 'Éditer', icon: pencil }
          delete: { name: delete, type: method, label: 'Supprimer', icon: trash }
          new: { name: new, type: method, label: 'Ajouter', icon: user-plus }
        dql_filter: 'entity.rank = 0'
        fields:
          - { property: 'enabled', label: 'Active' }
          - { property: 'username', label: 'Utilisateur' }
          - { property: 'name', label: 'Nom' }
          - { property: 'email', label: 'Contact' }
          - { property: 'formatedroles', label: 'Role'}
          - { property: 'formatedrank', label: 'Rang' }
          - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
          - { property: 'formatedevent', label: 'Évènement', type: string}
        title: 'Liste des %%entity_label%%'
        sort: ['enabled', 'DESC']
      show:
        title: '%%entity_label%% n°(#%%entity_id%%)'
        fields:
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom Utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { property: 'formatedroles', label: 'Role'}
          - { property: 'formatedrank', label: 'Rang' }
          - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
          - { property: 'event', label: 'Inscris à l''évènement'}
          - { property: 'enabled', label: 'Active', help: 'L''utilisateur est autorisé à se connecter'}
      form:
        fields:
          - { type: 'group', columns: 6, label: 'Informations personnelles', icon: 'user' }
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom Utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { type: 'group', columns: 5, label: 'Informations Complémentaires', icon: 'code' }
          - property: 'plainPassword'
            type: 'repeated'
            type_options:
              type: Symfony\Component\Form\Extension\Core\Type\PasswordType
              required: true
              first_options: { label: 'Mot de passe' }
              second_options: { label: 'Confirmer le mot de passe' }
              invalid_message: fos_user.password.mismatch
    Event:
      controller: App\Controller\EventBackendController
      class: App\Entity\Event
      label: 'Évènements'
      new:
        title: 'Créer un nouvel %%entity_label%%'
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
      search:
        sort: ['date', 'DESC']
      list:
        actions:
          show: { name: show, type: method, label: 'Plus', icon: eye }
          edit: { name: edit, type: method, label: 'Éditer', icon: pencil }
          delete: { name: delete, type: method, label: 'Supprimer', icon: trash }
          new: { name: new, type: method, label: 'Ajouter', icon: calendar-plus }
        fields:
          - { property: 'title', label: 'Titre' }
          - { property: 'description', label: 'Description'}
          - { property: 'date', label: 'Date', type: 'date' }
          - { property: 'hour', label: 'Heure', type: 'time' }
        title: 'Liste des %%entity_label%%'
        sort: ['date', 'DESC']
      show:
        title: '%%entity_label%% n°(#%%entity_id%%)'
        fields:
          - { property: 'title', label: 'Titre', type: 'text'}
          - { property: 'description', label: 'Description'}
          - { property: 'date', label: 'Date', type_options: {'format': 'ddMMyyyy', 'attr': {'class': 'datepicker'}} }
          - { property: 'hour', label: 'Heure' }
          - property: 'users'
            label: 'Utilisateurs'
            type: 'entity'
            type_options:
              class: App\Entity\User
      form:
        fields:
          - { type: 'group', columns: 6, label: 'Informations Textuelles', icon: 'info' }
          - { property: 'title', label: 'Titre', type: 'text'}
          - { property: 'description', label: 'Description'}
          - { type: 'group', columns: 6, label: 'Heure et participants', icon: 'calendar' }
          - { property: 'date', label: 'Date', type_options: {'format': 'ddMMyyyy', 'attr': {'class': 'datepicker'}} }
          - { property: 'hour', label: 'Heure' }
          - property: 'users'
            label: 'Utilisateurs'
            type: 'easyadmin_autocomplete'
    Project:
      class: App\Entity\Project
      label: 'Projets'
      new:
        title: 'Créer un nouveau %%entity_label%%'
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
      search:
        sort: ['statute', 'DESC']
      list:
        actions:
          show: { name: show, type: method, label: 'Plus', icon: eye }
          edit: { name: edit, type: method, label: 'Éditer', icon: pencil }
          delete: { name: delete, type: method, label: 'Supprimer', icon: trash }
          new: { name: new, type: method, label: 'Ajouter', icon: plus }
        fields:
          - { property: 'id', label: 'Identifiant' }
          - { property: 'statute', label: 'Status' }
          - { property: 'Users', label: 'Utilisateurs', type: 'array_json' }
        title: 'Liste des %%entity_label%%'
        sort: ['statute', 'DESC']
      show:
        title: '%%entity_label%% n°(#%%entity_id%%)'
        fields:
          - property: 'users'
            type: 'entity'
            type_options:
              class: App\Entity\User
          - property: 'statute'
      form:
        fields:
          - { type: 'group', columns: 6, label: 'Joueurs', icon: 'users' }
          - property: 'users'
            type: 'easyadmin_autocomplete'
          - { type: 'group', columns: 6, label: 'Type de Joueur', icon: 'info' }
          - property: 'statute'
            type: 'choice'
            type_options:
              expanded: true
              data: '0'
              choices: { 'Joueur': '0', 'Maître du Jeu': '1' }