# config/packages/easy_admin.yaml
easy_admin:
  formats:
    datetime: 'd/m/Y H:i:s'
  design:
    assets:
      favicon:
        path: '/bundles/easyadmin/images/projet/Logo Taliesin.webp'
        mime_type: 'image/webp'
  site_name: '<img src="/bundles/easyadmin/images/projet/Logo Taliesin.webp" />'
  entities:
    User:
      class: App\Entity\User
      controller: App\Controller\Admin\User\UserAdminController
      label: 'Utilisateur'
      new:
        title: 'Créer un nouvel %%entity_label%%'
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
      search:
        sort: ['enabled', 'DESC']
      list:
        fields:
          - { property: 'username', label: 'Utilisateur'}
          - { property: 'name', label: 'Nom' }
          - { property: 'email', label: 'Contact' }
          - { property: 'roles', label: 'Role', type: 'json_array' }
          - { property: 'rank', label: 'Rang' }
          - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
          - { property: 'enabled', label: 'Active' }
        title: 'Liste des %%entity_label%%s'
        sort: ['enabled', 'DESC']
      show:
        title: '%%entity_label%% n°(#%%entity_id%%)'
      form:
        fields:
          - { type: 'group', columns: 6, offset: 1, label: 'Informations personnelles', icon: 'user' }
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom Utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { type: 'group', columns: 5, label: 'Informations Complémentaires', icon: 'code' }
          - { property: 'plainPassword', type_options: { required: true }, type: 'password', label: 'Mot de passe'}
          - { property: 'rank', type: 'integer', label: 'Rang' }
          - { property: 'roles', label: 'Role', type: 'choice', choices: { 'Conseiller': 'ROLE_USER', 'Administrateur': 'ROLE_ADMIN' }}
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
    Orbis_Primus:
      class: App\Entity\User
      controller: App\Controller\Admin\User\UserAdminController
      label: 'Orbis Primus'
      new:
        title: 'Créer un nouvel %%entity_label%%'
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
      search:
        sort: ['enabled', 'DESC']
      list:
        dql_filter: 'entity.rank = 2'
        fields:
            - { property: 'enabled', label: 'Active' }
            - { property: 'username', label: 'Utilisateur' }
            - { property: 'name', label: 'Nom' }
            - { property: 'email', label: 'Contact' }
            - { property: 'roles', label: 'Role', type: 'json_array' }
            - { property: 'rank', label: 'Rang' }
            - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
        title: 'Liste des %%entity_label%%'
        sort: ['enabled', 'DESC']
      show:
        title: '%%entity_label%% n°(#%%entity_id%%)'
      form:
        fields:
          - { type: 'group', columns: 6, offset: 1, label: 'Informations personnelles', icon: 'user' }
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom Utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { type: 'group', columns: 5, label: 'Informations Complémentaires', icon: 'code' }
          - { property: 'plainPassword', type_options: { required: true }, type: 'password', label: 'Mot de passe'}
          - { property: 'rank', type: 'integer', label: 'Rang' }
          - { property: 'roles', label: 'Roles'}
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
    Orbis_Secondus:
      class: App\Entity\User
      controller: App\Controller\Admin\User\UserAdminController
      label: 'Orbis Secondus'
      new:
        title: 'Créer un nouvel %%entity_label%%'
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
      search:
        sort: ['enabled', 'DESC']
      list:
        dql_filter: 'entity.rank = 1'
        fields:
          - { property: 'enabled', label: 'Active' }
          - { property: 'username', label: 'Utilisateur' }
          - { property: 'name', label: 'Nom' }
          - { property: 'email', label: 'Contact' }
          - { property: 'roles', label: 'Role', type: 'json_array' }
          - { property: 'rank', label: 'Rang' }
          - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
        title: 'Liste des %%entity_label%%'
        sort: ['enabled', 'DESC']
      show:
        title: '%%entity_label%% n°(#%%entity_id%%)'
      form:
        fields:
          - { type: 'group', columns: 6, offset: 1, label: 'Informations personnelles', icon: 'user' }
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom Utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { type: 'group', columns: 5, label: 'Informations Complémentaires', icon: 'code' }
          - { property: 'plainPassword', type_options: { required: true }, type: 'password', label: 'Mot de passe'}
          - { property: 'rank', type: 'integer', label: 'Rang' }
          - { property: 'roles', label: 'Roles'}
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
    Orbis_Tertius:
      class: App\Entity\User
      controller: App\Controller\Admin\User\UserAdminController
      label: 'Orbis Tertius'
      new:
        title: 'Créer un nouvel %%entity_label%%'
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
      search:
        sort: ['enabled', 'DESC']
      list:
        dql_filter: 'entity.rank = 0'
        fields:
          - { property: 'enabled', label: 'Active' }
          - { property: 'username', label: 'Utilisateur' }
          - { property: 'name', label: 'Nom' }
          - { property: 'email', label: 'Contact' }
          - { property: 'roles', label: 'Role', type: 'json_array' }
          - { property: 'rank', label: 'Rang' }
          - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
        title: 'Liste des %%entity_label%%'
        sort: ['enabled', 'DESC']
      show:
        title: '%%entity_label%% n°(#%%entity_id%%)'
      form:
        fields:
          - { type: 'group', columns: 6, offset: 1, label: 'Informations personnelles', icon: 'user' }
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom Utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { type: 'group', columns: 5, label: 'Informations Complémentaires', icon: 'code' }
          - { property: 'plainPassword', type_options: { required: true }, type: 'password', label: 'Mot de passe'}
          - { property: 'rank', type: 'integer', label: 'Rang' }
          - { property: 'roles', label: 'Roles'}
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
    Event:
      class: App\Entity\Event
    Project:
      class: App\Entity\Project
