fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "vuillecardy@gmail.com"
        sender_name: "Collectif Taliesin"
    registration:
        confirmation:
            enabled: true
            from_email:
                address:        vuillecardy@gmail.com
                sender_name:    Inscription
    resetting:
        email:
            from_email:
                address:        vuillecardy@gmail.com
                sender_name:    Réinitialisation Mot de passe