easy_admin:
  site_name: '<img src="/bundles/easyadmin/images/projet/Logo Taliesin.webp" /> Collectif Taliesin'
  formats:
    datetime: 'd/m/Y H:i:s'
    date: 'd/m/Y'
    time: 'H:i'
  list:
    collapse_actions: true
    batch_actions:
      delete: { name: delete, label: 'Supprime', icon: trash }