easy_admin:
  entities:
    Booking:
      class: App\Entity\Booking
      controller: App\Controller\BookingBackendController
      label: 'Évènement'
      new:
        title: 'Créer un nouvel %%entity_label%%'
        fields:
          - { type: 'group', columns: 6, label: 'Informations', icon: 'info' }
          - { property: 'title', label: 'Titre' }
          - { property: 'description', label: 'Description' }
          - { type: 'group', columns: 6, label: 'Paramètres', icon: 'users' }
          - { property: 'beginat', label: 'Commence le ', type: 'datetime', type_options: { widget: 'single_text' } }
          - property: 'users'
            label: 'Participants'
      edit:
        title: 'Modifier l'' %%entity_label%% n°%%entity_id%%'
        fields:
          - { type: 'group', columns: 6, label: 'Informations', icon: 'info' }
          - { property: 'title', label: 'Titre' }
          - { property: 'description', label: 'Description' }
          - { type: 'group', columns: 6, label: 'Paramètres', icon: 'users' }
          - { property: 'beginat', label: 'Commence le ', type: 'datetime', type_options: { widget: 'single_text' } }
          - property: 'users'
            label: 'Participants'
      search:
        sort: ['beginAt', 'ASC']
      list:
        filters:
          - { property: 'title', label: 'Titre' }
          - { property: 'description', label: 'Description' }
          - { property: 'beginAt', label: 'Commence le' }
        batch_actions:
          severalClear: { name: severalClear, label: 'Vider', icon: user-times }
        actions:
          clear: { name: clear, type: method, label: 'Vider', icon: user-times }
          show: { name: show, type: method, label: 'Plus', icon: eye }
          edit: { name: edit, type: method, label: 'Éditer', icon: pencil }
          delete: { name: delete, type: method, label: 'Supprimer', icon: trash }
          new: { name: new, type: method, label: 'Ajouter', icon: plus }
        fields:
          - { property: 'title', label: 'Titre' }
          - { property: 'description', label: 'Description' }
          - { property: 'beginAt', label: 'Commence le ' }
          - property: 'users'
            label: 'Participants'
        title: 'Liste des %%entity_label%%s'
        sort: ['beginAt', 'ASC']
      show:
        title: '%%entity_label%% n°%%entity_id%%'
        fields:
          - { property: 'title', label: 'Titre' }
          - { property: 'description', label: 'Description' }
          - { property: 'beginat', label: 'Commence le ', type: 'datetime', type_options: { widget: 'single_text' } }
          - { property: 'createdat', label: 'Créé le ', type: 'datetime', type_options: { widget: 'single_text' } }
          - property: 'users'
            label: 'Participants'