easy_admin:
  design:
    assets:
      css:
        - 'bundles/easyadmin/custom.css'
      favicon:
        path: '/media/Logo Taliesin.webp'
        mime_type: 'image/webp'
    menu:
      - label: 'Entités'
      - label: 'Utilisateurs'
        icon: 'users'
        children:
          - { label: 'Orbis Primus', icon: 'certificate', entity: 'Orbis_Primus' }
          - { label: 'Orbis Secondus', icon: 'asterisk', entity: 'Orbis_Secondus'}
          - { label: 'Orbis Tertius', icon: 'times', entity: 'Orbis_Tertius'}
      - label: 'Projets'
        icon: 'project-diagram'
        children:
          - { label: 'Maître du Jeu', icon: 'crown', entity: 'Maitre_du_jeu' }
          - { label: 'Joueur', icon: 'gamepad', entity: 'Joueur'}
      - label: 'Site Web'
      - { label: 'Accueil', route: 'home', icon: 'home' }
      - { label: 'Projet Oddyssey', route: 'project_index', icon: 'flask' }
      - { label: 'L''équipe', route: 'equipe_index', icon: 'user-friends' }
      - { label: 'Planning', route: 'booking_calendar', icon: 'calendar-check' }