easy_admin:
  entities:
    Event:
      help: 'Attention : Pour supprimer un évènement, vous devez retirer les utilisateurs y participants'
      controller: App\Controller\EventBackendController
      class: App\Entity\Event
      label: 'Évènements'
      new:
        title: 'Créer un nouvel %%entity_label%%'
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
      search:
        sort: ['date', 'DESC']
      list:
        actions:
          show: { name: show, type: method, label: 'Plus', icon: eye }
          edit: { name: edit, type: method, label: 'Éditer', icon: pencil }
          delete: { name: delete, type: method, label: 'Supprimer', icon: trash }
          new: { name: new, type: method, label: 'Ajouter', icon: calendar-plus }
        fields:
          - { property: 'title', label: 'Titre' }
          - { property: 'description', label: 'Description'}
          - { property: 'date', label: 'Date', type: 'date' }
          - { property: 'hour', label: 'Heure', type: 'time' }
          - { property: 'users', label: 'Participants'}
        title: 'Liste des %%entity_label%%'
        sort: ['date', 'DESC']
      show:
        title: '%%entity_label%% n°(#%%entity_id%%)'
        fields:
          - { property: 'title', label: 'Titre', type: 'text'}
          - { property: 'description', label: 'Description'}
          - { property: 'date', label: 'Date', type_options: {'format': 'ddMMyyyy', 'attr': {'class': 'datepicker'}} }
          - { property: 'hour', label: 'Heure' }
          - property: 'users'
            label: 'Utilisateurs'
      form:
        fields:
          - { type: 'group', columns: 6, label: 'Informations Textuelles', icon: 'info' }
          - { property: 'title', label: 'Titre', type: 'text'}
          - { property: 'description', label: 'Description'}
          - { type: 'group', columns: 6, label: 'Heure et participants', icon: 'calendar' }
          - { property: 'date', label: 'Date', type_options: {'format': 'ddMMyyyy', 'attr': {'class': 'datepicker'}} }
          - { property: 'hour', label: 'Heure' }
          - property: 'users'
            label: 'Utilisateurs'
            type: 'easyadmin_autocomplete'