easy_admin:
  entities:
    Maitre_du_jeu:
      help: 'Attention : Pour supprimer un projet, vous devez retirer les utilisateurs y participants'
      class: App\Entity\Project
      controller: App\Controller\ProjectBackendController
      label: 'Projet'
      new:
        title: 'Créer un nouveau %%entity_label%%'
        fields:
          - { type: 'group', columns: 6, label: 'Type de Joueur', icon: 'info' }
          - property: 'statute'
            type: 'choice'
            label: 'Fonction'
            type_options:
              expanded: true
              data: '1'
              choices: { 'Maître du Jeu': '1' }
      edit:
        title: 'Modifier le %%entity_label%% n°%%entity_id%%'
        fields:
          - { type: 'group', columns: 6, label: 'Type de Joueur', icon: 'info' }
          - property: 'statute'
            type: 'choice'
            label: 'Fonction'
            type_options:
              expanded: true
              data: '1'
              choices: { 'Joueur': '0', 'Maître du Jeu': '1' }
      search:
        sort: ['id', 'DESC']
      list:
        dql_filter: 'entity.statute = 1'
        batch_actions:
          severalClear: { name: severalClear, label: 'Vider', icon: user-times }
        actions:
          toggle: { name: toggle, type: method, label: 'basculer en Joueur', icon: sliders-h }
          clear: { name: clear, type: method, label: 'Vider', icon: user-times }
          show: { name: show, type: method, label: 'Plus', icon: eye }
          edit: { name: edit, type: method, label: 'Éditer', icon: pencil }
          delete: { name: delete, type: method, label: 'Supprimer', icon: trash }
          new: { name: new, type: method, label: 'Ajouter', icon: plus }
        fields:
          - { property: 'id', label: 'Numéro' }
          - { property: 'statutetype', label: 'Fonction' }
          - { property: 'users', label: 'Utilisateurs' }
        title: 'Liste des %%entity_label%%s'
        sort: ['id', 'DESC']
      show:
        title: '%%entity_label%% n°%%entity_id%%'
        fields:
          - property: 'users'
            label: 'Utilisateurs'
          - property: 'statutetype'
            label: 'Fonction'
      form:
        fields:
          - { type: 'group', columns: 6, label: 'Joueurs', icon: 'users' }
          - property: 'users'
            type: 'easyadmin_autocomplete'
            label: 'Participants'