easy_admin:
  entities:
    Projects:
      class: App\Entity\Project
      controller: App\Controller\ProjectBackendController
      label: 'Projet'
      new:
        title: 'Créer un nouveau %%entity_label%%'
        fields:
          - { type: 'group', columns: 6, label: 'Type de Joueur', icon: 'info' }
          - property: 'statute'
            type: 'choice'
            label: 'Fonction'
            type_options:
              expanded: true
              choices: { 'Maître du Jeu': '1', 'Joueur': '0' }
      edit:
        title: 'Modifier le %%entity_label%% n°%%entity_id%%'
        fields:
          - { type: 'group', columns: 6, label: 'Type de Joueur', icon: 'info' }
          - property: 'statute'
            type: 'choice'
            label: 'Fonction'
            type_options:
              expanded: true
              data: '1'
              choices: { 'Joueur': '0', 'Maître du Jeu': '1' }
      search:
        sort: ['id', 'ASC']
      list:
        help: 'Utilisation des filtres : [FONCTIONS] 0 = Joueur | 1 = Maître de Jeu'
        filters:
          - { property: 'id', label: 'Numéro' }
          - { property: 'statute', label: 'Fonctions' }
          - { property: 'users', label: 'Utilisateurs' }
        batch_actions:
          severalClear: { name: severalClear, label: 'Vider', icon: user-times }
          severalToggle: { name: severalToggle, label: 'Basculer', icon: sliders-h }
        actions:
          toggle: { name: toggle, type: method, label: 'basculer', icon: sliders-h }
          clear: { name: clear, type: method, label: 'Vider', icon: user-times }
          show: { name: show, type: method, label: 'Plus', icon: eye }
          edit: { name: edit, type: method, label: 'Éditer', icon: pencil }
          delete: { name: delete, type: method, label: 'Supprimer', icon: trash }
          new: { name: new, type: method, label: 'Ajouter', icon: plus }
        fields:
          - { property: 'id', label: 'Numéro' }
          - { property: 'statutetype', label: 'Fonction' }
          - { property: 'users', label: 'Utilisateurs' }
        title: 'Liste des %%entity_label%%s'
        sort: ['id', 'ASC']
      show:
        title: '%%entity_label%% n°%%entity_id%%'
        fields:
          - property: 'users'
            label: 'Utilisateurs'
          - property: 'statutetype'
            label: 'Fonction'
      form:
        fields:
          - { type: 'group', columns: 6, label: 'Joueurs', icon: 'users' }
          - { property: 'users', label: 'Participants' }