easy_admin:
  entities:
    Users:
      class: App\Entity\User
      controller: App\Controller\UserBackendController
      label: 'Utilisateur'
      new:
        title: 'Créer un nouvel %%entity_label%%'
        fields:
          - { type: 'group', columns: 6, label: 'Informations personnelles', icon: 'user' }
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom d''utilisateur'}
          - { property: 'email', type: 'email', label: 'Email' }
          - { type: 'group', columns: 5, label: 'Informations Complémentaires', icon: 'code' }
          - property: 'project'
            label: 'Participe au projet'
            type: 'entity'
            type_options:
              class: App\Entity\Project
          - property: 'rank'
            type: 'choice'
            type_options:
              expanded: true
              choices: { 'Orbis Primus': '2', 'Orbis Secondus': '1', 'Orbis Tertius': '0' }
          - property: 'roles'
            type: 'choice'
            type_options:
              expanded: true
              multiple: true
              choices: { 'Utilisateur': '[ROLE_USER]', 'Administrateur': 'ROLE_ADMIN' }
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
          - { type: 'group', columns: 11, label: 'Informations confidentielles', icon: 'user-lock' }
          - property: 'plainPassword'
            type: 'repeated'
            type_options:
              type: Symfony\Component\Form\Extension\Core\Type\PasswordType
              required: true
              first_options: { label: 'Mot de passe' }
              second_options: { label: 'Confirmer le mot de passe' }
              invalid_message: fos_user.password.mismatch
      edit:
        title: 'Modifier l''%%entity_label%% n°%%entity_id%%'
        fields:
          - { type: 'group', columns: 6, label: 'Informations personnelles', icon: 'user' }
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom d''utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { type: 'group', columns: 5, label: 'Informations Complémentaires', icon: 'code' }
          - property: 'project'
            label: 'Participe au projet'
            type: 'entity'
            type_options:
              class: App\Entity\Project
          - property: 'rank'
            type: 'choice'
            type_options:
              expanded: true
              choices: { 'Orbis Primus': '2', 'Orbis Secondus': '1', 'Orbis Tertius': '0' }
          - property: 'roles'
            type: 'choice'
            type_options:
              expanded: true
              multiple: true
              choices: { 'Utilisateur': '[ROLE_USER]', 'Administrateur': 'ROLE_ADMIN' }
          - { property: 'enabled', type: 'checkbox', label: 'Active', help: 'Active : Permettre à l''utilisateur de se connecter'}
      search:
        sort: ['username', 'ASC']
      list:
        help: 'Utilisation des filtres : [RANG] Orbis Tertius = 0, Orbis Secondus = 1, Orbis Primus = 2 | [ROLES] ROLE_ADMIN, ROLE_USER'
        filters:
          - { property: 'enabled', label: 'Active' }
          - { property: 'username', label: 'Pseudo' }
          - { property: 'email', label: 'Email' }
          - { property: 'rank', label: 'Rang', type: 'integer' }
          - { property: 'roles', label: 'Rôle', type: 'array'}
        batch_actions:
          severalPromote: { name: severalPromote, label: 'Promouvoir', icon: award }
          severalDemote: { name: severalDemote, label: 'Rétrograder', icon: angle-double-down }
        actions:
          promote: { name: promote, type: method, label: 'Promouvoir', icon: award }
          demote: { name: demote, type: method, label: 'Rétrograder', icon: angle-double-down }
          show: { name: show, type: method, label: 'Plus', icon: eye }
          edit: { name: edit, type: method, label: 'Éditer', icon: pencil }
          delete: { name: delete, type: method, label: 'Supprimer', icon: trash }
          new: { name: new, type: method, label: 'Ajouter', icon: user-plus }
        fields:
          - { property: 'enabled', label: 'Active' }
          - { property: 'username', label: 'Utilisateur' }
          - { property: 'email', label: 'Contact' }
          - { property: 'formatedrank', label: 'Rang' }
          - { property: 'formatedroles', label: 'Rôle'}
          - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
          - { property: 'formatedproject', label: 'Projet'}
        title: 'Liste des %%entity_label%%'
        sort: ['username', 'ASC']
      show:
        title: '%%entity_label%% n°%%entity_id%%'
        fields:
          - { property: 'firstname', label: 'Prénom'}
          - { property: 'lastname', label: 'Nom'}
          - { property: 'username', label: 'Nom d''utilisateur'}
          - { property: 'email', type: 'email', label: 'Email'}
          - { property: 'formatedroles', label: 'Rôle'}
          - { property: 'formatedrank', label: 'Rang' }
          - { property: 'last_login', label: 'Dernière connexion', type: 'datetime' }
          - { property: 'enabled', label: 'Active', help: 'L''utilisateur est autorisé à se connecter'}